# Generated by Django 4.2.3 on 2023-07-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='books',
            field=models.ManyToManyField(null=True, related_name='members', to='book_app.book'),
        ),
    ]
